### ISSUE TITLE
Simple Block Codes doesn't work

### ISSUE THREAD

**Issue by killerpommes** [Lunatrius/Schematica#75]
Hi, 
i can't get the Simple Block Codes working.
i try to block the save and print feature on my 1.8 Spigot Server
I use the codes in the essentials motd

Can you check if they are working?
Or how can i get them working?

**Comment by Lunatrius** [comment]
MOTD is the text text bellow the server name, that won't work. You need a plugin/something that sends the player a message when he connects to the server.

**Comment by killerpommes** [comment]
The MOTD from Essentials is a text that is shown when i joined the server.
It is like a welcome message.

**Comment by Lunatrius** [comment]
Is it a public server? Tried checking the code, can't really find much.

**Comment by killerpommes** [comment]
No Its not a public server, sorry.
It is only a local server for testing stuff.

**Comment by Lunatrius** [comment]
```
[09:43:26] [Client thread/INFO] [Schematica]: Printer is disabled on this server.
[09:43:26] [Client thread/INFO]: [CHAT] §0§2§0§0§e§fNO
[09:43:26] [Client thread/INFO] [Schematica]: Saving is disabled on this server.
[09:43:26] [Client thread/INFO]: [CHAT] §0§2§1§0§e§fNO
```

Check the log for messages.

**Comment by killerpommes** [comment]
i see none of this.

**Comment by Lunatrius** [comment]
.minecraft/logs/fml-client-latest.log

**Comment by killerpommes** [comment]
i dont see these messages.

[10:22:47] [Client thread/DEBUG] [Schematica/]: Message #1: §r§0a§r§2b§r§0c§r§0d§r§ee§r§ff§r
[10:22:47] [Client thread/DEBUG] [Schematica/]: Message #2: §r§0A§r§2B§r§1C§r§0D§r§eE§r§fF§r
[10:22:47] [Client thread/DEBUG] [Schematica/]: Message #3: §r
[10:22:47] [Client thread/DEBUG] [Schematica/]: Message #4: §r
[10:22:47] [Client thread/DEBUG] [Schematica/]: Message #5: §rWelcome§r
i put letters between the color codes to see if the color codes are working.
On the next two lines are the simple block codes

I can try to run a simple server and send you the IP, if ti would help you

**Comment by Lunatrius** [comment]
I did have the correct assumption. Essential strips all but the last color code in a series of color codes.
You'll have to find a plugin that doesn't change the color codes. The SBC plugin would make it easy, but there doesn't seem to be any intention on fixing fromgate/SBC#1.

**Comment by killerpommes** [comment]
Do you have a motd mod in mind, that would work?

**Comment by Lunatrius** [comment]
Never used Bukkit, but I'm sure there must be something that works on the plugin repository.

**Comment by killerpommes** [comment]
But how can i confirm if the codes are working at all?

**Comment by Lunatrius** [comment]
When you login with Schematica on the client you'll see `[Client thread/INFO] [Schematica/]: Printer is disabled on this server.` in the log. This one will show up in the console because it's logging level INFO.

**Comment by killerpommes** [comment]
Ok thanks.

**Comment by dewick** [comment]
[Client thread/DEBUG] [Schematica/]: Message #1: �0�2�0�0�e�f�r
[Client thread/INFO] [Schematica/]: Printer is disabled on this server.

Well, I disabled printer on server, it also says in forge log, that printer is disabled, I'm still able to use printer in game without any restrictions.

Tried on Schematica-1.8-1.7.5.118-universal

**Comment by Lunatrius** [comment]
Full log (at least everything after logging in)?

**Comment by dewick** [comment]
Here is full log: http://grief.cz/paste.txt

At the end you can see loaded schema **Loaded Shipyard Nabaal.schematic [w:215,h:137,l:517]**
and then NoCheatPlus (NCP) screaming when printer is launched

**Comment by Lunatrius** [comment]
Fixed in d2a0d16f926d0c9b562e81d36f970fa12f5657ef. Looks like something changed in 1.8 that causes the client to receive the messages faster than in 1.7.10.

**Comment by dewick** [comment]
@Lunatrius Thank you for fixing it!

**Comment by LFassbinder** [comment]
I have tried a lot of different configurations and MOTD plugins but I still get every time message with §r in the beginning of the line. In this case color codes doesn't work (((. I use spigot 1.8.8 server.

**Comment by Lunatrius** [comment]
They have been broken in forever if you send the messages using `player.sendMessage`. You'll have to either construct a chat packet manually or use this [hack](https://gist.github.com/Lunatrius/ffa4508ffe9053c54e6a).

**Comment by LFassbinder** [comment]
Thank you for answer, but I am not good in programming. Maybe you know some plugin which can be used as Block Codes sender instead of standard one? If not, then can you explain how to put that hack on my server. I use one of the standard servers (1.8.8 spigot) from hosting control panel. As I understand SBC is the message which doesn't have a sender name. I hope that it is possible at least with command blocks and extra plugin for messages, am I right?

**Comment by Lunatrius** [comment]
The problem with SBC messages right now is, all the modifiers are truncated - they used to work fine before 1.7 started using JSON for the messages.

Bukkit/Spigot manually construct the message, applying the colors one after another as they appear in the message. The same part of the message can't have different colors, which overrides the previously applied colors.

I would release a plugin for this myself, but the hack above is not what I want to release - it's unreliable and may stop working at any time. Some people suggested BungeeCord to construct the proper packet, but the documentation for that is pretty much useless.

**Comment by LFassbinder** [comment]
Ok, I got it. So I hope you will release the plugin soon. Because I have no idea how to make that java file works for a server )

**Comment by Lunatrius** [comment]
https://www.spigotmc.org/resources/schematicaplugin.14411/

**Comment by LFassbinder** [comment]
Could not load 'plugins\SchematicaPlugin-1.8-1.1.0.2-bungeecord.jar  http://pastebin.com/bC3QCBqb

**Comment by Lunatrius** [comment]
All plugin issues should be posted [here](https://github.com/Lunatrius/SchematicaPlugin/issues) instead.

Anyway, as the name of the file already implicates it's a **BungeeCord** plugin. If you want a Bukkit/Spigot alternative I've written [this **hack**](https://gist.github.com/ffa4508ffe9053c54e6a) before I actually write the BungeeCord plugin.

I won't be distributing a compiled version of the hack. You'll have to [compile it yourself](https://www.spigotmc.org/wiki/spigot-plugin-development/) or ask someone to do it for you.
